// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnvhushwcqevrymotcva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhudmh1c2h3Y3FldnJ5bW90Y3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDMzOTMsImV4cCI6MjA2Njc3OTM5M30.r5B5gjNL1RxStTjsFWh70VCkaq_-7I3Xzq4xgmPj8Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);